#!/usr/bin/env python3
"""Write src/audio/synth_tables_saturn.h: tables for the SCSP MIDI synthesizer.

  s_fnsTable[c]  FNS register value for c cents above an octave boundary
                 (0 <= c < 1200): 1024 * (2^(c/1200) - 1)
  s_levelTable[v] attenuation in TL units (0.375 dB each) for a MIDI level
                 v (velocity, volume, expression): 40 * log10(127 / v)

Run: saturn/tools/make_synth_tables.py > src/audio/synth_tables_saturn.h
"""

import math

TL_STEP_DB = 0.375


def main():
    fns = [round(1024 * (2 ** (c / 1200) - 1)) for c in range(1200)]
    fns = [min(v, 1023) for v in fns]
    level = [255] + [min(255, round(40 * math.log10(127 / v) / TL_STEP_DB)) for v in range(1, 128)]

    print('/** @file src/audio/synth_tables_saturn.h Tables for the SCSP MIDI synthesizer.')
    print(' *')
    print(' * Generated by saturn/tools/make_synth_tables.py; do not edit. */')
    print()
    print('#ifndef SYNTH_TABLES_SATURN_H')
    print('#define SYNTH_TABLES_SATURN_H')
    print()
    print('/* FNS for c cents above an octave boundary: 1024 * (2^(c/1200) - 1) */')
    print('static const uint16 s_fnsTable[1200] = {')
    for i in range(0, 1200, 12):
        print('\t' + ', '.join('%4d' % v for v in fns[i:i + 12]) + ',')
    print('};')
    print()
    print('/* attenuation in TL units (0.375 dB) of a MIDI level: 40 * log10(127 / v) */')
    print('static const uint8 s_levelTable[128] = {')
    for i in range(0, 128, 16):
        print('\t' + ', '.join('%3d' % v for v in level[i:i + 16]) + ',')
    print('};')
    print()
    print('#endif /* SYNTH_TABLES_SATURN_H */')


if __name__ == '__main__':
    main()
